config/routes.rb
Rails.application.routes.draw do
  resources :package_test_reports
  resources :homes
  post 'package_descriptions/:id', :to=>"package_descriptions#update"
  get "package_descriptions/generate_pdf"
  resources :package_descriptions
  resources :packages

   root 'homes#index'

end

app/models/package_description.rb
class PackageDescription < ActiveRecord::Base
    belongs_to :package_test_report
    has_one :package
end

app/controllers/package_descriptions_controller.rb
class PackageDescriptionsController < ApplicationController
  before_action :set_package_description, only: [:show, :edit, :update, :destroy]

  # GET /package_descriptions
  # GET /package_descriptions.json
  def index
    @package_descriptions = PackageDescription.all

  end

  # GET /package_descriptions/1
  # GET /package_descriptions/1.json
  def show
     # respond_to do |format|
      # format.html
      # format.pdf do
        # pdf = Prawn::Document.new
        # send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
      # end
    # end

  end

  # GET /package_descriptions/new
  def new
    @package_description = PackageDescription.new
  end

  # GET /package_descriptions/1/edit
  def edit
  end
  def generate_pdf

   @package_description = PackageDescription.find params[:format]
   respond_to do |format|
     format.html
      format.pdf do
        pdf = ContentPdf.new(@package_description,view)
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
      end
    end
 end
  # POST /package_descriptions
  # POST /package_descriptions.json
  def create
     client_id = PackageTestReport.where(id: request.env["HTTP_REFERER"].split(".").last).last
     #client_id = PackageTestReport.find_by_client_name params[:client_name]
        #client_id = PackageTestReport.find_by_client_name params[:package_pack_type] if client_id.blank?
       @package_description = PackageDescription.new(:package_number => managed_params, :package_name=>params[:package_pack_type], :package_test_report_id=>client_id.id)

     respond_to do |format|
      if @package_description.save
        format.html { redirect_to @package_description, notice: 'Package description was successfully created.' }
        format.json { render :show, status: :created, location: @package_description }
      else
        format.html { render :new }
        format.json { render json: @package_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_descriptions/1
  # PATCH/PUT /package_descriptions/1.json
  def update
       respond_to do |format|
      if @package_description.update(:package_number => managed_params, :package_name=>params[:package_pack_type])
        format.html { redirect_to @package_description, notice: 'Package description was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_description }
      else
        format.html { render :edit }
        format.json { render json: @package_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_descriptions/1
  # DELETE /package_descriptions/1.json
  def destroy
    @package_description.destroy
    respond_to do |format|
      format.html { redirect_to package_descriptions_url, notice: 'Package description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_description
      @package_description = PackageDescription.find(params[:id])
    end
    def managed_params
     p_array = []; t=0
    params.map {| x |
      t =t+1
       p_array.push(params["p#{t}"])
       }
       params["arranged_params"] = p_array
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def package_description_params
      params.require(:package_description).permit!
    end
end

app/helpers/package_descriptions_helper.rb
module PackageDescriptionsHelper
  def client_name(name)
    (PackageTestReport.find name).client_name
  end
  def homes
    Home.first
  end
  
end

app/views/package_descriptions/_authorization.html.erb
<% if not @package_description.package_test_report.blank? %>
      <% pckg = @package_description.package_test_report %>
		<p><b>Customer</b></p>
		<p><%= pckg.client_name%></p>
		<p><%= pckg.customer_details%></p>
        <p><b>Testing Perfomed By :</b></p>
        <p><%= pckg.testing_performed_by%></p>
        <p><b>Test Date :</b></p>
        <p><%= pckg.test_date%></p>
        <p><b>Packaeg Identifiers :</b></p>
        <p><%= pckg.package_details%></p>
        <table border = "2">
	      <tr>
		    <td><%= pckg.manufacture_details%></td>
	 	  </tr>
        </table>
        <br/>
        <table border = "2" style="width:850px">
	      <tr>
		    <td align="center">Approval Authorization</td>
		  </tr>
	    </table>
		  <p>The testing conducted on subject U.N. Hazardous Material packaging compiles with applicable hazardous material.
      regultion, provision, and/or <br> special permits and/or approvals.</p>
        <table border = "2" style="width:850px">
	      <tr>
		    <td align="center">Test Purpose</td>
		  </tr>
	    </table>
		<p>The purpose of this testing conducted on subject U.N. Hazardous Material packaging was to quality/certify this packaging based on <br>United Nations Test Requirements for <%= pckg.packaging_group1%>
			 Criteria. The package product is listed as a <%= pckg.packaging_group2 %></p>
			 <table border = "2" style="width:850px">
	      <tr>
		    <td align="center">Personal Present During Testing</td>
		  </tr>
	    </table>
	    <p>H. Perry Hock, President and Technical Director, gh Package & Product Testing and Consulting, INC.<br>
      Tomithy Glasmeier, Laboratory Manager, gh Packaging & Product Testing and Consulting, INC.<br>
      Carol Metz, Supervisor, Materials Testing, gh Packaging & Product Testing and Consulting, INC.<br>
      Ronald Sorrel, Test Engineer, gh Packaging & Product Testing and Consulting, INC.<br>
      Andrew Galish, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.<br>
      Caarin Galish, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.<br>
      Joseph Becker, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.</p>
	    <table border = "2" style="width:850px">
	      <tr>
		    <td align="center">Test Equipment</td>
		  </tr>
	    </table>
	    <p><img alt="Brand" src="/assets/ppp.jpg"></p>
    <%end%>

app/views/package_descriptions/_form.html.erb
<%= form_for(@package_description) do |f| %>
  <% if @package_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@package_description.errors.count, "error") %> prohibited this package_description from being saved:</h2>

      <ul>
      <% @package_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :package_number %><br>
    <%= f.text_field :package_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_descriptions/_home.html.erb
    <!--<% home = homes %>
      
        <%= raw(home.istm_no) %>
        <%= raw(home.istm_name) %>
        <%= raw(home.company_name) %>
        <%= raw(home.date) %><br /><br />-->
    

app/views/package_descriptions/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Package Description</h1>
<%= form_tag action: :update, method: :put do %>
<% k = eval(@package_description.package_number)%>
<%= label_tag :package_pack_type%>
<%= text_field_tag :package_pack_type%>
<ol type="1">
<li> The Exterior corrugated cartor<%= text_field_tag :p1,k[0] %>contains everything listed below in one exterior box as presented for testing.</li>
<li>
	<ol type="A">
	<li>10 - inner chipboard carton<%= text_field_tag :p2,k[1]%>.Each inner chipboard box contains:</li>
	
	<ol type="I">
	<li>7 - positive means of closure Ziploc bags with pouch<%= text_field_tag :p3,k[2]%></li>
	<ol type="i">
	<li>2 - ultra vials<%= text_field_tag :p4,k[3]%></li>
	<ol type="a">
	<li>2 - scoops<%= text_field_tag :p5,k[4]%></li>
	<li>2 - ultra vial caps<%= text_field_tag :p6,k[5]%></li>
	</ol>
	<li>1 - Para Pak vial<%= text_field_tag :p7,k[6]%></li>
	<ol type="a">
	<li>1 - Spork<%= text_field_tag :p8,k[7]%></li>
	<li>2 - Para Pak vial cap <%= text_field_tag :p9,k[8]%></li>
	</ol>
	<li>Instruction set<%= text_field_tag :p10,k[9]%></li>
	</ol>
	<li>Instruction sheet<%= text_field_tag :p11,k[10]%></li>
	<li>1 - Release key <%= text_field_tag :p12,k[11]%></li>
	</ol>
	<li>2 - Inner chipboard carton<%= text_field_tag :p13,k[12]%>. Each inner chipboard box contains:</li>
	<ol type="I">
		<li>7 - positive means of closure Ziploc bags with pouch<%= text_field_tag :p14,k[13]%> </li>
		<ol type="i">
			<li>2 - ultra vials<%= text_field_tag :p15,k[14]%> </li>
			<ol type="a">
				<li>2 - scoops<%= text_field_tag :p16,k[15]%></li>
				<li>2 - ultra vial caps<%= text_field_tag :p17,k[16]%></li>
				</ol>
				<li>1 - Para Pak vial<%= text_field_tag :p18,k[17]%></li>
				<ol type="a">
     <li>1 - Spork<%= text_field_tag :p19,k[18]%></li>
     <li>1 - Para Pak vial cap<%= text_field_tag :p20,k[19]%></li>
					</ol>
	<li>Instruction set<%= text_field_tag :p21,k[20]%></li>
   <li>1 - dropper bottle<%= text_field_tag :p22,k[21]%></li>
   <ol type ="a">
   	<li>1 - dropper bottle tip<%= text_field_tag :p23,k[22]%></li>
   	<li>1 - dropper bottle cap<%= text_field_tag :p24,k[23]%></li>
   	</ol>
			</ol>

		<li>Instruction sheet<%= text_field_tag :p25,k[24]%></li>
		<li>1 - Release key<%= text_field_tag :p26,k[25]%> </li>
		</ol>
		<li>4 - Absorbent pads<%= text_field_tag :p27,k[26]%></li>
	</ol>
	</ol>
	<p><b>Alternate Pach 3414</b></p>
	<ol type= "1">
    <li>The Exterior corrugated carton<b>(P/N:<%= text_field_tag :p28, k[27] %>)</b> contains everything listed below in one exteriro box as presented for testign</li>
		</ol>
		<ol type = "A">
		  <li>4 - Absorbent pads<%= text_field_tag :p29, k[28]%></li>
		  <li>1 - folded instruction sheet</li>
		  <li>200 - positive means of closure Ziploc bags pouch <%= text_field_tag :p30, k[29]%>. Each Ziploc bag with pouch contains:
		     <ol type ="i">
                <li>1 - Para Pak vial<%= text_field_tag :p31, k[30]%>
                	<ol type="a">
                         <li>1 - Spork <%= text_field_tag :p32, k[31]%></li>
                         <li>1 - Para Pak vial cap <%= text_field_tag :p33, k[32]%></li>
                		</ol>
                </li>
                <li>1 - Instruction sheet <%= text_field_tag :p34, k[33]%></li>
             </ol>
		  </li>
			</ol>
	<%= submit_tag 'Submit'%>
<%end%>



<%= link_to 'Show', @package_description %> |
<%= link_to 'Back', package_descriptions_path %>

app/views/package_descriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Package Descriptions</h1>

<table>
  <thead>
    <tr>
      <th>Package number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @package_descriptions.each do |package_description| %>
      <tr>
        <td><%= package_description.package_number %></td>
        <td><%= link_to 'Show', package_description %></td>
        <td><%= link_to 'Edit', edit_package_description_path(package_description) %></td>
        <td><%= link_to 'Destroy', package_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Package description', new_package_description_path %>

app/views/package_descriptions/new.html.erb
<div class="container">
</table>
<br/>
<table border = "2" style="width:1000px" >
<tr>
<td align="center" height="30px"><b>Section 2- Package Description</b></td>
</tr>
</table>
<div>
<div id="combine">
    <label for='name'>Combination packaging</label>
</div>
<div id="life">
    <label for='name'>life cycle of 24 months</label>
</div>
<div id="new">
    <label for='name'>New Design Testing</label>
  <br />
</div>
</div>
<style>
#combine label{
float: left;
margin-left: 40px;
font-weight: normal;
}
#life label{
float: left;
margin-left: 200px;
font-weight: normal;
}
#new label{
float: left;
margin-left: 300px;
font-weight: normal;
}
</style>
<br/>
<p>The Packaging System listed below is submitted for UN Certification and has several parts as follows</p>
<br />


<%= form_tag action: :create do | p |%>
<!--<%= text_field_tag :client_name, client_name(params[:format]), disabled: true%><br/>-->
<div class="form-group">
<%= label_tag :package_pack_type%>
<%= text_field_tag :package_pack_type%><br \>
</div>
<ol type="1">
  <div class="form-group">
<li> The Exterior corrugated cartor <%= text_field_tag :p1 %> contains everything listed below in one exterior box as presented for testing.</li>
</div>
 <ol type="A">
   <div class="form-group">
 <li>10 - inner chipboard carton <%= text_field_tag :p2, nil, placeholder: "Enter Package No" %>.Each inner chipboard box contains:</li>
</div>
 <ol type="I">
   <div class="form-group">
 <li>7 - positive means of closure Ziploc bags with pouch <%= text_field_tag :p3 %></li>
 </div>
 <ol type="i">
   <div class="form-group">
 <li>2 - ultra vials <%= text_field_tag :p4%></li>
 </div>
 <ol type="a">
   <div class="form-group">
 <li>2 - scoops <%= text_field_tag :p5%></li>
 </div>
 <div class="form-group">
 <li>2 - ultra vial caps <%= text_field_tag :p6%></li>
 </div>
 </ol>
  <div class="form-group">
 <li>1 - Para Pak vial <%= text_field_tag :p7%></li>
 </div>

 <ol type="a">
    <div class="form-group">
 <li>1 - Spork <%= text_field_tag :p8%></li>
 </div>
  <div class="form-group">
 <li>2 - Para Pak vial cap <%= text_field_tag :p9%></li>
 </div>
 </ol>
  <div class="form-group">
 <li>Instruction set <%= text_field_tag :p10%></li>
 </div>
 </ol>
  <div class="form-group">
 <li>Instruction sheet <%= text_field_tag :p11%></li>
 </div>
  <div class="form-group">
 <li>1 - Release key <%= text_field_tag :p12%></li>
 </div>
 </ol>
  <div class="form-group">
 <li>2 - Inner chipboard carton <%= text_field_tag :p13%>. Each inner chipboard box contains:</li>
 </div>
 <ol type="I">
    <div class="form-group">
  <li>7 - positive means of closure Ziploc bags with pouch <%= text_field_tag :p14%> </li>
</div>
  <ol type="i">
     <div class="form-group">
   <li>2 - ultra vials <%= text_field_tag :p15%> </li>
 </div>
   <ol type="a">
      <div class="form-group">
    <li>2 - scoops <%= text_field_tag :p16%></li>
  </div>
   <div class="form-group">
    <li>2 - ultra vial caps <%= text_field_tag :p17%></li>
  </div>
    </ol>
     <div class="form-group">
    <li>1 - Para Pak vial <%= text_field_tag :p18%></li>
  </div>
    <ol type="a">
       <div class="form-group">
     <li>1 - Spork <%= text_field_tag :p19%></li>
   </div>
    <div class="form-group">
     <li>1 - Para Pak vial cap <%= text_field_tag :p20%></li>
   </div>
     </ol>
      <div class="form-group">
 <li>Instruction set <%= text_field_tag :p21%></li>
 </div>
  <div class="form-group">
   <li>1 - dropper bottle <%= text_field_tag :p22%></li>
 </div>
   <ol type ="a">
      <div class="form-group">
    <li>1 - dropper bottle tip <%= text_field_tag :p23%></li>
  </div>
   <div class="form-group">
    <li>1 - dropper bottle cap <%= text_field_tag :p24%></li>
  </div>
    </ol>
   </ol>
 <div class="form-group">
  <li>Instruction sheet <%= text_field_tag :p25%></li>
</div>
   <div class="form-group">
  <li>1 - Release key <%= text_field_tag :p26%> </li>
</div>
  </ol>
   <div class="form-group">
  <li>4 - Absorbent pads <%= text_field_tag :p27%></li>
</div>
 </ol>
 </ol>
  <div class="form-group">
 <p><b>Alternate Pach 3414</b></p>
 </div>
 <ol type= "1">
    <div class="form-group">
    <li>The Exterior corrugated carton <%= text_field_tag :p28 %> contains everything listed below in one exteriro box as presented for testign</li>
  </div>
  </ol>
  <ol type = "A">
     <div class="form-group">
    <li>4 - Absorbent pads <%= text_field_tag :p29%></li>
  </div>
   <div class="form-group">
    <li>1 - folded instruction sheet</li>
  </div>
   <div class="form-group">
    <li>200 - positive means of closure Ziploc bags pouch <%= text_field_tag :p30%>. Each Ziploc bag with pouch contains:
    </div>
       <ol type ="i">
          <div class="form-group">
                <li>1 - Para Pak vial <%= text_field_tag :p31%>
                </div>
                 <ol type="a">
                    <div class="form-group">
                         <li>1 - Spork <%= text_field_tag :p32%></li>
                       </div>
                        <div class="form-group">
                         <li>1 - Para Pak vial cap <%= text_field_tag :p33%></li>
                       </div>
                  </ol>
                </li>
                 <div class="form-group">
                <li>1 - Instruction sheet <%= text_field_tag :p34%></li>
              </div>
             </ol>
    </li>
   </ol>
 <%= submit_tag 'Submit', :class=>"btn btn-primary"%>
 <!--<%= link_to 'Back', package_test_reports_path , :class=>"btn btn-info" %>-->
<%end%>

<!--<%= link_to 'Back', package_descriptions_path , :class=>"btn btn-info" %>-->
</div>

app/views/package_descriptions/show.html.erb
<div class="container">
  <div class="page-break">
    <%= render "layouts/home_form"%>
    <%= render "home"%>
    <%= render "authorization"%>
    <b><%= @package_description.package_name %></b>
    <% k = eval(@package_description.package_number)%>
      <ol type="1">
        <li> The Exterior corrugated cartor <b>(P/N:<%= k[0] %>)</b> contains everything listed below in one exterior box as presented for testing.</li>
      <li>
	  <ol type="A">
	    <li>10 - inner chipboard carton <b>(P/N:<%= k[1] %>)</b> .Each inner chipboard box contains:</li>
	  <ol type="I">
	    <li>7 - positive means of closure Ziploc bags with pouch <b>(P/N:<%= k[2] %>)</b> </li>
	    <ol type="i">
	      <li>2 - ultra vials <b>(P/N:<%= k[3] %>)</b> </li>
	      <ol type="a">
	       <li>2 - scoops <b>(P/N:<%= k[4] %>)</b> </li>
	       <li>2 - ultra vial caps <b>(P/N:<%= k[5] %>)</b> </li>
	       </ol>
	       <li>1 - Para Pak vial <b>(P/N:<%= k[6] %>)</b> </li>
	       <ol type="a">
	<li>1 - Spork <b>(P/N:<%= k[7] %>)</b> </li>
	<li>2 - Para Pak vial cap  <b>(P/N:<%= k[8] %>)</b> </li>
	</ol>
	<li>Instruction set <b>(P/N:<%= k[9] %>)</b> </li>
	</ol>
	<li>Instruction sheet <b>(P/N:<%= k[10] %>)</b> </li>
	<li>1 - Release key  <b>(P/N:<%= k[11] %>)</b> </li>
	</ol>
	<li>2 - Inner chipboard carton <b>(P/N:<%= k[12] %>)</b> . Each inner chipboard box contains:</li>
	<ol type="I">
		<li>7 - positive means of closure Ziploc bags with pouch <b>(P/N:<%= k[13] %>)</b>  </li>
		<ol type="i">
			<li>2 - ultra vials <b>(P/N:<%= k[14] %>)</b>  </li>
			<ol type="a">
				<li>2 - scoops <b>(P/N:<%= k[15] %>)</b> </li>
				<li>2 - ultra vial caps <b>(P/N:<%= k[16] %>)</b> </li>
				</ol>
				<li>1 - Para Pak vial <b>(P/N:<%= k[17] %>)</b> </li>
				<ol type="a">
     <li>1 - Spork <b>(P/N:<%= k[18] %>)</b> </li>
     <li>1 - Para Pak vial cap <b>(P/N:<%= k[19] %>)</b> </li>
					</ol>
	<li>Instruction set <b>(P/N:<%= k[20] %>)</b> </li>
   <li>1 - dropper bottle <b>(P/N:<%= k[21] %>)</b> </li>
   <ol type ="a">
   	<li>1 - dropper bottle tip <b>(P/N:<%= k[22] %>)</b> </li>
   	<li>1 - dropper bottle cap <b>(P/N:<%= k[23] %>)</b> </li>
   	</ol>
			</ol>

		<li>Instruction sheet <b>(P/N:<%= k[24] %>)</b> </li>
		<li>1 - Release key <b>(P/N:<%= k[25] %>)</b>  </li>
		</ol>
		<li>4 - Absorbent pads <b>(P/N:<%= k[26] %>)</b> </li>
	</ol>
	</ol>

	<p><b>Alternate Pach 3414</b></p>
	<ol type= "1">
    <li>The Exterior corrugated carton<b>(P/N:<%= k[27] %>)</b> contains everything listed below in one exteriro box as presented for testign</li>
		</ol>
<ol type = "A">
		  <li>4 - Absorbent pads<b>(P/N:<%= k[28] %>)</b>%></li>
		  <li>1 - folded instruction sheet</li>
		  <li>200 - positive means of closure Ziploc bags pouch <b>(P/N:<%= k[29] %>)</b>. Each Ziploc bag with pouch contains:
		     <ol type ="i">
                <li>1 - Para Pak vial<b>(P/N:<%= k[30] %>)</b>
                	<ol type="a">
                         <li>1 - Spork <b>(P/N:<%= k[31] %>)</b></li>
                         <li>1 - Para Pak vial cap <b>(P/N:<%= k[32] %>)</b></li>
                		</ol>
                </li>
                <li>1 - Instruction sheet <b>(P/N:<%= k[33] %>)</b></li>
             </ol>
		  </li>
			</ol>
<% table_view  = @package_description.package%>
<% if not table_view.blank? %>

<table border = '1'>
<tr>
<td>manufacturer</td>
<td><%= table_view.manufacturer %></td>
</tr>
<tr>
<td>manufacturer_location</td>
<td><%= table_view.manufacturer_location %></td>
</tr>
<tr>
<td>material</td>
<td><%= table_view.material %></td>
</tr>

<tr>
<td>box_style</td>
<td><%= table_view.box_style %></td>
</tr>

<tr>
<td>part</td>
<td><%= table_view.part %></td>
</tr>

<tr>
<td>bmc</td>
<td><%= table_view.bmc %></td>
</tr>

<tr>
<td>number_of_walls</td>
<td><%= table_view.number_of_walls %></td>
</tr>

<tr>
<td>board_cliper</td>
<td><%= table_view.board_cliper %></td>
</tr>

<tr>
<td>basis_weight_of_each_liner_and_medium</td>
<td><%= table_view.basis_weight_of_each_liner_and_medium %></td>
</tr>

<tr>
<td>inside_liner</td>
<td><%= table_view.inside_liner %></td>
</tr>


<tr>
<td>first_medium</td>
<td><%= table_view.first_medium %></td>
</tr>

<tr>
<td>outside_liner</td>
<td><%= table_view.outside_liner %></td>
</tr>

<tr>
<td>combined_basis_weight</td>
<td><%= table_view.combined_basis_weight %></td>
</tr>

<tr>
<td>flute</td>
<td><%= table_view.flute %></td>
</tr>

<tr>
<td>method_of_joining_panels</td>
<td><%= table_view.method_of_joining_panels %></td>
</tr>

<tr>
<td>manufacturers_joint</td>
<td><%= table_view.manufacturers_joint %></td>
</tr>

<tr>
<td>flap_size</td>
<td><%= table_view.flap_size %></td>
</tr>

<tr>
<td>location</td>
<td><%= table_view.location %></td>
</tr>

<tr>
<td>dimensions_external</td>
<td><%= table_view.dimensions_external%></td>
</tr>

<tr>
<td>dimensions_internal</td>
<td><%= table_view.dimensions_internal %></td>
</tr>

<tr>
<td>top_flap_inner_gap_or_meet</td>
<td><%= table_view.top_flap_inner_gap_or_meet %></td>
</tr>

<tr>
<td>top_flap_outer_overlap_or_meet</td>
<td><%= table_view.top_flap_outer_overlap_or_meet %></td>
</tr>

<tr>
<td>bottom_flap_inner_gap_or_meet </td>
<td><%= table_view.bottom_flap_inner_gap_or_meet %></td>
</tr>

<tr>
<td>bottom_flap_outer_overlap_or_meet </td>
<td><%= table_view.bottom_flap_outer_overlap_or_meet %></td>
</tr>

<tr>
<td>stacking_height</td>
<td><%= table_view.stacking_height  %></td>
</tr>

<tr>
<td>handles_material_type_number_and_position</td>
<td><%= table_view.handles_material_type_number_and_position %></td>
</tr>

<tr>
<td>tare_weight</td>
<td><%= table_view.tare_weight %></td>
</tr>

<tr>
<td>closure_method_of_box </td>
<td><%= table_view.closure_method_of_box %></td>
</tr>

<tr>
<td>top</td>
<td><%= table_view.top %></td>
</tr>

<tr>
<td>bottom</td>
<td><%= table_view.bottom%> </td>
</tr>
<%= link_to "Edit table", edit_package_path(table_view)%>



<br />
<tr>
				<% table_view.images.each do | image |%>
				<td><%= image_tag image.photo(:medium) %></td>
				<%end%>
				</tr>
				</table>
<br />
<% end %>

<div class="pdf_exclude">

<%= link_to 'add tables', {:controller=>"packages", :action=>"new", :id => @package_description.id}, :class=>"btn btn-success" %>


<!--<%= link_to 'Back', package_descriptions_path %>-->




<!-- <%= link_to 'Edit', edit_package_description_path(@package_description) %> |
<%= link_to 'Back', package_descriptions_path %> -->
<%= link_to 'See Pdf', package_description_path(@package_description,:format => "pdf") %>
	</div>
</div>
</div>
<style>
@media print {
  .page-break {
    display: block;
    /*page-break-before: always; */
  }
  .pdf_exclude {
        display: none;
  }
}
</style>