config/routes.rb
Rails.application.routes.draw do
  resources :package_test_reports
  resources :homes
  post 'package_descriptions/:id', :to=>"package_descriptions#update"
  get "package_descriptions/generate_pdf"
  resources :package_descriptions
  resources :packages

   root 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    #@home = Home.where(:company_name => "Alphabate").last
    @home = Home.last
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to root_url, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to homes_url, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:istm_no, :istm_name, :company_name, :date)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<div class="container">

<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <table border = "5"  align="center" style="height:200px;width:900px">
<td >


<div class="col-sm-6">
      <img src="/assets/tests.jpg"  align="top" style="width:100px;height:100px;">
  <br /> <br />
        <label for='name'><b>Packaging and Product<br>Testing And Consulting,Inc<b>
        <p> 4090, Thunderbird lane</p>
        <p> Fairfield, OH 45014</p>
        <p> Phone: (513)870-0080 </p>
        <p> Fax (513) 870-0017 </p>
        <p> ISO 17025 ACCREDITED </p> </label>

  <div class="field">
    <%= f.label :istm_no %><br>
    <%= f.text_field :istm_no %>
  </div>
  <div class="field">
    <%= f.label :istm_name %><br>
    <%= f.text_field :istm_name %>

    </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
</div>

<div class="col-sm-6 pull-right">
    <img class="img-responsive" alt="Brand" src="/assets/tests.jpg" style="width:700px;height:500px" >
</div>
</td>
</table>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/homes/_home_form.html.erb
<div class="container">

  <table border = "5"  align="center" style="height:200px;width:900px">
<td >


<div class="col-sm-6">
      <img src="/assets/tests.jpg"  align="top" style="width:100px;height:100px;">
  <br /> <br />
        <label for='name'><b>Packaging and Product<br>Testing And Consulting,Inc<b>
        <p> 4090, Thunderbird lane</p>
        <p> Fairfield, OH 45014</p>
        <p> Phone: (513)870-0080 </p>
        <p> Fax (513) 870-0017 </p>
        <p> ISO 17025 ACCREDITED </p> </label>
<% f = @home%>

  <div class="field">
    <%= "istm_no" %><br>
    <%= f.istm_no %>
  </div>
  <div class="field">
    <%=  "istm_name" %><br>
    <%= f.istm_name %>

    </div>
  <div class="field">
    <%= "company_name" %><br>
    <%= f.company_name %>
  </div>
  <div class="field">
    <%= "date" %><br>
    <%= f.date %>
  </div>
</div>

<div class="col-sm-6 pull-right">
    <img class="img-responsive" alt="Brand" src="/assets/tests.jpg" style="width:700px;height:500px" >
</div>
</td>
</table>
</div>
<% end %>
</div>

app/views/homes/edit.html.erb
<h1>Cover Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="panel-heading">
  <% if not @home.blank?%>

<%= render "form" %>
<% end %>
</div>
    <!--<%= link_to 'Add Cover Page ', new_home_path, :class=>"btn btn-primary" %>-->

     <%= link_to 'Create Package', new_package_test_report_path, :class=>"btn btn-primary" %>
      <!-- <%= link_to 'create a package', new_package_description_path, :class=>"btn btn-primary" %> -->
    </div>

app/views/homes/new.html.erb
<h1></h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Istm no:</strong>
  <%= @home.istm_no %>
</p>

<p>
  <strong>Istm name:</strong>
  <%= @home.istm_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @home.company_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @home.date %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>