config/routes.rb
Rails.application.routes.draw do
  resources :package_test_reports
  resources :homes
  post 'package_descriptions/:id', :to=>"package_descriptions#update"
  get "package_descriptions/generate_pdf"
  resources :package_descriptions
  resources :packages

   root 'homes#index'

end

app/models/package_test_report.rb
class PackageTestReport < ActiveRecord::Base
  has_one :package_description
end

app/controllers/package_test_reports_controller.rb
class PackageTestReportsController < ApplicationController
  before_action :set_package_test_report, only: [:show, :edit, :update, :destroy]

  # GET /package_test_reports
  # GET /package_test_reports.json
  def index
    @package_test_reports = PackageTestReport.all
  end

  # GET /package_test_reports/1
  # GET /package_test_reports/1.json
  def show
  end

  # GET /package_test_reports/new
  def new
    @package_test_report = PackageTestReport.new
  end

  # GET /package_test_reports/1/edit
  def edit
  end

  # POST /package_test_reports
  # POST /package_test_reports.json
  def create
    @package_test_report = PackageTestReport.new(package_test_report_params)

    respond_to do |format|
      if @package_test_report.save
        format.html { redirect_to package_test_report_path(@package_test_report), notice: 'successfully created.' }
        # format.html { redirect_to new_package_description_path params[:pt_test] = @package_test_report.id, notice: 'Package test report was successfully created.' }
        format.json { render :show, status: :created, location: @package_test_report }
      else
        format.html { render :new }
        format.json { render json: @package_test_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_test_reports/1
  # PATCH/PUT /package_test_reports/1.json
  def update
    respond_to do |format|
      if @package_test_report.update(package_test_report_params)
        format.html { redirect_to @package_test_report, notice: 'Package test report was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_test_report }
      else
        format.html { render :edit }
        format.json { render json: @package_test_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_test_reports/1
  # DELETE /package_test_reports/1.json
  def destroy
    @package_test_report.destroy
    respond_to do |format|
      format.html { redirect_to package_test_reports_url, notice: 'Package test report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_test_report
      @package_test_report = PackageTestReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_test_report_params
      params.require(:package_test_report).permit! #(:customer_details, :testing_performed_by, :test_date, :package_details, :manufacture_details, :authorized_signature, :release_date, :packaging_group1, :packaging_group2, :personal_present_during_test)
    end
end

app/helpers/package_test_reports_helper.rb
module PackageTestReportsHelper
end

app/views/package_test_reports/_form.html.erb
<%= form_for(@package_test_report) do |f| %>
  <% if @package_test_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@package_test_report.errors.count, "error") %> prohibited this package_test_report from being saved:</h2>

      <ul>
      <% @package_test_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <img src="/assets/top.jpg"  align="top" style="width:1150px;height:250px">
  <div class="form-horizontal">
    <div class="field">
        <div class="form-group">
            <h5><%= f.label :client_name, :class=>"col-sm-2 control-label" %></h5>
          <div class="col-sm-10">
            <%= f.text_field :client_name, :class=>"form-control" %>
          </div>
        </div>
    </div>
  <div class="field">
    <div class="form-group">
        <h5><%= f.label :customer_details, :class=>"col-sm-2 control-label" %></h5>
    <div class="col-sm-10">
    <%= f.text_field :customer_details, :class=>"form-control" %>
  </div>
  </div>
</div>
  <div class="field">
    <div class="form-group">
    <h5><%= f.label :testing_performed_by, :class=>"col-sm-2 control-label" %></h5>
    <div class="col-sm-10">
    <%= f.text_field :testing_performed_by, :class=>"form-control" %>
  </div>
  </div>
</div>



  <div class="field">
      <div class="form-group">
    <h5><%= f.label :test_date, :class=>"col-sm-2 control-label" %></h5>
    <div class="col-sm-10">
    <%= f.date_select :test_date, :class=>"form-control" %>
  </div>
</div>
</div>


  <div class="field">
    <div class="form-group">
    <h5><%= f.label :package_details ,:class=>"col-sm-2 control-label"%></h5>
    <div class="col-sm-10">
    <%= f.text_field :package_details,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
    <div class="form-group">
    <h5><%= f.label :manufacture_details,:class=>"col-sm-2 control-label" %></h5>
      <div class="col-sm-10">
    <%= f.text_field :manufacture_details,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
    <div class="form-group">
    <h5><%= f.label :authorized_signature,:class=>"col-sm-2 control-label" %></h5>
      <div class="col-sm-10">
    <%= f.text_field :authorized_signature,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
      <div class="form-group">
    <h5><%= f.label :release_date,:class=>"col-sm-2 control-label" %></h5>
    <div class="col-sm-10">
    <%= f.date_select :release_date,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
    <div class="form-group">
  <h5><%= f.label :packaging_group1 ,:class=>"col-sm-2 control-label"%></h5>
  <div class="col-sm-10">
    <%= f.text_field :packaging_group1,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
    <div class="form-group">
    <h5><%= f.label :packaging_group2,:class=>"col-sm-2 control-label" %></h5>
      <div class="col-sm-10">
    <%= f.text_field :packaging_group2,:class=>"form-control" %>
  </div>
</div>
</div>
  <div class="field">
      <div class="form-group">
    <h5><%= f.label :personal_present_during_test,:class=>"col-sm-2 control-label" %></h5>
        <div class="col-sm-10">
    <%= f.text_field :personal_present_during_test,:class=>"form-control" %>
  </div>
</div>
</div>
  <img src="/assets/bottom.jpg"  align="top" style="width:1150px; height:350px;" position="300px,300px">
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_test_reports/edit.html.erb
<h1>Edit Synopsis</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @package_test_report %> |
<%= link_to 'Back', package_test_reports_path %>-->

app/views/package_test_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Package Test Reports</h1>

<table>
  <thead>
    <tr>
    	<th>Customer Name</th>
      <th>Customer details</th>
      <th>Testing performed by</th>
      <th>Test date</th>
      <th>Package details</th>
      <th>Manufacture details</th>
      <th>Authorized signature</th>
      <th>Release date</th>
      <th>Packaging group1</th>
      <th>Packaging group2</th>
      <th>Personal present during test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @package_test_reports.each do |package_test_report| %>
      <tr>
      	<td><%= package_test_report.client_name %></td>
        <td><%= package_test_report.customer_details %></td>
        <td><%= package_test_report.testing_performed_by %></td>
        <td><%= package_test_report.test_date %></td>
        <td><%= package_test_report.package_details %></td>
        <td><%= package_test_report.manufacture_details %></td>
        <td><%= package_test_report.authorized_signature %></td>
        <td><%= package_test_report.release_date %></td>
        <td><%= package_test_report.packaging_group1 %></td>
        <td><%= package_test_report.packaging_group2 %></td>
        <td><%= package_test_report.personal_present_during_test %></td>
        <td><%= link_to 'Show', package_test_report %></td>
        <td><%= link_to 'Edit', edit_package_test_report_path(package_test_report) %></td>
        <td><%= link_to 'Destroy', package_test_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Package test report', new_package_test_report_path %>

app/views/package_test_reports/new.html.erb
<h1></h1>

<%= render 'form' %>

<%= link_to 'Back', package_test_reports_path %>

app/views/package_test_reports/show.html.erb
<div class="container">
      <% pckg = @package_test_report %>
  <p><b>Customer</b></p>
  <p><%= pckg.client_name%></p>
  <p><%= pckg.customer_details%></p>
        <p><b>Testing Perfomed By :</b></p>
        <p><%= pckg.testing_performed_by%></p>
        <p><b>Test Date :</b></p>
        <p><%= pckg.test_date%></p>
        <p><b>Package Identifiers :</b></p>
        <p><%= pckg.package_details%></p>
        <table border = "2">
       <tr>
      <td><%= pckg.manufacture_details%></td>
     </tr>
        </table>
        <br/>
        <table border = "2" style="width:1000px">
       <tr>
      <td align="center"><h5><b>Approval Authorization</b></h5></td>
    </tr>
     </table>
      <p><h5>The testing conducted on subject U.N. Hazardous Material packaging compiles with applicable hazardous material.
      regultion, provision, and/or special <br> permits and/or approvals.</h5></p>
        <table border = "2" style="width:1000px">
       <tr>
      <td align="center"><h5><b>Test Purpose</h5></b></td>
    </tr>
     </table>
  <p>The purpose of this testing conducted on subject U.N. Hazardous Material packaging was to quality/certify this packaging based on United Nations <br>
<div class="form-group">
 Test Requirements for <b><%= pckg.packaging_group1 %></b> Criteria. The package product is listed as a
  <b><%= pckg.packaging_group2 %></b>
</div>



    <table border = "2" style="width:1000px">
       <tr>
      <td align="center"><h5><b>Personal Present During Testing</h5></b></td>
    </tr>
     </table>
      <p>H. Perry Hock, President and Technical Director, gh Package & Product Testing and Consulting, INC.<br>
      Tomithy Glasmeier, Laboratory Manager, gh Packaging & Product Testing and Consulting, INC.<br>
      Carol Metz, Supervisor, Materials Testing, gh Packaging & Product Testing and Consulting, INC.<br>
      Ronald Sorrel, Test Engineer, gh Packaging & Product Testing and Consulting, INC.<br>
      Andrew Galish, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.<br>
      Caarin Galish, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.<br>
      Joseph Becker, Laboratory Technician, gh Packaging & Product Testing and Consulting, INC.</p>
     <table border = "2" style="width:1000px"  style="height:10px">
       <tr>
      <td align="center"><h5><b>Test Equipment</h5></b></td>
    </tr>
     </table>
     <p><img alt="Brand" src="/assets/ppp.jpg"></p>
    </div>

<br /><br />
<%= link_to 'Edit', edit_package_test_report_path(@package_test_report), :class=>"btn btn-success" %> |
<!--<%= link_to 'Back', package_test_reports_path, :class=>"btn btn-success" %> |-->
<%= link_to 'Add Package Description', new_package_description_path(format: @package_test_report.id ) , :class=>"btn btn-success" %>|
<%= link_to 'See in pdf', package_test_report_path(@package_test_report, format: "pdf"), :class=>"btn btn-success" %>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Customer details:</strong>
  <%= @package_test_report.customer_details %>
</p>

<p>
  <strong>Testing performed by:</strong>
  <%= @package_test_report.testing_performed_by %>
</p>

<p>
  <strong>Test date:</strong>
  <%= @package_test_report.test_date %>
</p>

<p>
  <strong>Package details:</strong>
  <%= @package_test_report.package_details %>
</p>

<p>
  <strong>Manufacture details:</strong>
  <%= @package_test_report.manufacture_details %>
</p>

<p>
  <strong>Authorized signature:</strong>
  <%= @package_test_report.authorized_signature %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @package_test_report.release_date %>
</p>

<p>
  <strong>Packaging group1:</strong>
  <%= @package_test_report.packaging_group1 %>
</p>

<p>
  <strong>Packaging group2:</strong>
  <%= @package_test_report.packaging_group2 %>
</p>

<p>
  <strong>Personal present during test:</strong>
  <%= @package_test_report.personal_present_during_test %>
</p>

<%= link_to 'Edit', edit_package_test_report_path(@package_test_report) %> |
<%= link_to 'Back', package_test_reports_path %> -->